apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-app
  labels:
    app: demo-app
    lab: kubernetes-lab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-app
        lab: kubernetes-lab
    spec:
      containers:
      - name: demo-app
        image: demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080