kind: Service
apiVersion: v1
metadata:
  name: demo-app
  labels:
    app: demo-app
    lab: kubernetes-lab
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: demo-app