apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql
  labels:
    app: mysql
    lab: kubernetes-lab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        lab: kubernetes-lab
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits :
            cpu: 0.5
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: test
        ports:
        - containerPort: 3306
          name: mysql
